#!/usr/bin/env bash

# After adding a new third-party dependency, developers should run this script.
# NOTE: why on earth we would want to crashed the terminal if it failed without seeing it output?
# set -o errexit -o nounset -o pipefail

# bazel run //requirements:runtime.update
# bazel run //requirements:requirements.all.update
# bazel run //:gazelle_python_manifest.update

# New uv script
bazel run @uv -- lock --python 3.10
bazel run //:gazelle